### ISSUE TITLE
hover 마커의 상세 정보 받아오기

### ISSUE THREAD

**Issue by norangLemon** [WhereToday/front#24]
api를 통하여 hover된 마커의 상세 정보를 받아서 띄워준다.

**Comment by sarah950716** [comment]
상세정보라 하면 마커를 클릭했을 시 왼쪽에서 나오는 사이드바에 띄우는 정보를 말씀하시는건가요???

**Comment by norangLemon** [comment]
아뇨, 툴팁으로 띄워주는걸 말하는거에요ㅋㅋ

**Comment by sarah950716** [comment]
아하...네넹!

**Comment by sarah950716** [comment]
이게 문제가 있어요!! 제가 원래 상세 정보 띄워주는 부분을 구현했는데 google api로 정보를 가져올 때 누락되는 것들이 너무 많아서 그런거였어요! 그래서 디비에 찾아보니까 있는 장소더라구요! place/detail api로 디비에서 가져오는 부분을 만들어줘야 할 것 같아요!

**Comment by sarah950716** [comment]
아...이게 google maps api상에 제한이 있어서 그러네요! 디비에서 가져오는 api자체가 있어야 하겠네요...ㅜㅜ
